import { ClientProviders } from "@/components/clientProviders";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const dynamic = 'force-dynamic';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  )
}
