import { Layout } from "react-grid-layout";

// Kept out of the registry so layout data can be read without importing the
// widget components.
export type WidgetLayoutDefault = Partial<Layout> &
  Pick<Layout, "w" | "h"> & { isResizable?: boolean };

export const WIDGET_LAYOUT_DEFAULTS: Record<string, WidgetLayoutDefault> = {
  "live-info": { w: 3, h: 2, minW: 3, minH: 2 },
  "hive-price-chart": { w: 6, h: 5.8, minW: 4, minH: 1 },
  "fund-and-supply": { w: 3, h: 1.2, minW: 2, minH: 0.5 },
  "hive-parameters": { w: 3, h: 1.2, minW: 2, minH: 1 },
  "blockchain-dates": { w: 3, h: 1.2, minW: 2, minH: 1 },
  "market-data": { w: 4, h: 1.4, minW: 3, minH: 1 },
  "last-blocks": { w: 6, h: 8.3, minW: 6, minH: 8 },
  "top-witnesses": { w: 2.95, h: 13, minW: 2, minH: 6 },
  "top-communities": { w: 2.95, h: 5.8, minW: 2, minH: 3 },
  "top-accounts": { w: 3, h: 11, minW: 2, minH: 11 },
  "tx-stats": { w: 6, h: 5, minW: 3, minH: 4 },
  "transfer-volume": { w: 6, h: 5, minW: 3, minH: 4 },
  tvl: { w: 6, h: 3, minW: 3, minH: 3 },
  "network-hp-distribution": { w: 3, h: 6.7, minW: 2, minH: 5 },
  "network-growth": { w: 6, h: 3.3, minW: 3, minH: 3 },
  "hp-momentum": { w: 6, h: 5, minW: 3, minH: 4 },
  "daily-active-users": { w: 6, h: 3.3, minW: 3, minH: 3 },
  "account-retention-funnel": { w: 6, h: 3.3, minW: 3, minH: 3 },
  "network-author-retention": { w: 6, h: 8, minW: 3, minH: 4 },
  "op-mix": { w: 6, h: 3.3, minW: 3, minH: 3 },
  "network-rc-utilization": { w: 6, h: 3.3, minW: 3, minH: 3 },
  "network-content-volume": { w: 6, h: 5, minW: 3, minH: 4 },
  "network-engagement": { w: 6, h: 5, minW: 3, minH: 4 },
  "network-dapp-usage": { w: 6, h: 7, minW: 3, minH: 5 },
  "voting-activity": { w: 3, h: 5.8, minW: 2, minH: 4 },
  searches: { w: 6, h: 11.9, minW: 4, minH: 3 },
  "watched-proposals": { w: 3, h: 6, minW: 2, minH: 3 },
  "my-proposal-votes": { w: 3, h: 6, minW: 2, minH: 3 },
  "witness-schedule": { w: 6, h: 9, minW: 3, minH: 4 },
  "witness-health": { w: 3, h: 6, minW: 2, minH: 3 },
  "my-wallet": { w: 3, h: 8, minW: 2, minH: 1 },
  "my-balance-history": { w: 3, h: 10.5, minW: 2, minH: 1 },
  "my-recurring-transfers": { w: 3, h: 8, minW: 2, minH: 1 },
  "my-hp-delegations": { w: 3, h: 8, minW: 2, minH: 1 },
  "my-rc-delegations": { w: 3, h: 8, minW: 2, minH: 1 },
  "my-authorities": { w: 3, h: 8, minW: 2, minH: 1 },
  "my-recent-activity": { w: 3, h: 7, minW: 2, minH: 3 },
  "my-rc-footprint": { w: 6, h: 8, minW: 3, minH: 3 },
  "my-content-activity": { w: 6, h: 8, minW: 3, minH: 3 },
  "my-rc-consumption": { w: 6, h: 8, minW: 3, minH: 3 },
  "my-financial-summary": { w: 6, h: 8, minW: 3, minH: 3 },
  "my-pending-rewards": { w: 3, h: 11, minW: 2, minH: 1 },
  "my-notifications": { w: 3, h: 9, minW: 2, minH: 4 },
  "my-account-snapshot": { w: 3, h: 6, minW: 2, minH: 3 },
  "my-top-posts": { w: 3, h: 8, minW: 2, minH: 3 },
  "my-communities": { w: 3, h: 7, minW: 2, minH: 3 },
  "my-posting-activity": { w: 3, h: 8, minW: 2, minH: 3 },
  "my-social-interactions": { w: 6, h: 13, minW: 3, minH: 3 },
  "my-community-activity": { w: 6, h: 8, minW: 3, minH: 3 },
  "my-hp-activity": { w: 4, h: 6, minW: 2, minH: 1 },
  "top-holders": { w: 3, h: 8, minW: 2, minH: 3 },
  "board-header": { w: 12, h: 2, minW: 4, minH: 2, isResizable: true },
  "profile-banner": { w: 6, h: 2, minW: 3, minH: 2, isResizable: true },
  glossary: { w: 3, h: 5, minW: 2, minH: 2, isResizable: true },
  title: { w: 4, h: 1, minW: 3, minH: 1, isResizable: true },
  markdown: { w: 4, h: 4, minW: 2, minH: 2, isResizable: true },
  "quick-links": { w: 4, h: 4, minW: 2, minH: 3, isResizable: true },
  spacer: { w: 1, h: 2 },
  separator: { w: 12, h: 1, isResizable: true },
  image: { w: 4, h: 5, minW: 2, minH: 2, isResizable: true },
  note: { w: 4, h: 3, minW: 2, minH: 2, isResizable: true },
  "labeled-divider": { w: 12, h: 1, minW: 3, minH: 1, isResizable: true },
  button: { w: 3, h: 2, minW: 2, minH: 1, isResizable: true },
};
